### ISSUE TITLE
Split model training from randomness

### ISSUE THREAD

**Issue by Diggsey** [mgeisler/lipsum#71]
Training the model with "learn" is relatively slow (much slower than generating new words) so ideally you could train it once, and then use the same model to generate several sequences with different seeds.

However, this is not possible with the current API, because the seed is supplied when you first construct the MarkovChain, and cannot be changed after that point.

AFAICT, the "learn()" function is completely deterministic (it does not use the RNG) so this is a suboptimal design.

I would suggest removing the `rng` field from the `MarkovChain` entirely, and instead pass the RNG when you construct the `Words` iterator. This way you can train a model once, and then generate several sequences of text with different seeds. This should also make the `lipsum_words_from_seed` function much faster, even when not using a custom model.

**Comment by mgeisler** [comment]
Hi @Diggsey,

Thanks for reporting this! Your analysis sounds spot on — and I like that `lipsum_words_from_seed` can reuse the thread-local `LOREM_IPSUM_CHAIN` variable this way.

Would you be up for restructuring things as you suggest?

**Comment by Diggsey** [comment]
Yeah, it will be a breaking change though.

**Comment by mgeisler** [comment]
> Yeah, it will be a breaking change though.

That's okay, especially since the `lipsum_*` functions will stay unchanged, right?

The few dependencies of the crate seem to use those high-level functions, so they should have no problem upgrading.
